#!/bin/bash

while [ 1 ] ; do
curl http://chupr.iotfox.ru/chubrWorker.cgi?method=addData_devId=testStand_temp=`cat /sys/class/thermal/thermal_zone0/temp`_memUsed=`free | grep Mem | awk '{print $3}'`_cpu=` top -b -n1 | grep "Cpu(s)" | awk '{print $2 + $3  +$4}'`
sleep 10
done
